### ISSUE TITLE
{}转义问题

### ISSUE THREAD

**Issue by Mrliu88888888** [arajar/format#2]
const auto reqBody = util::Format(R"({{"query":{{"range":{{"timestamp":{{"lt":{0}}}}})", s);
这样转换才是正确，而不是
const auto reqBody = util::Format(R"({{"query":{{"range":{{"timestamp":{{"lt":{0}}}}}}}}})", s);

**Comment by wolf-hunter404** [comment]
我对源码做了调整，改为{}占位
Format("this test msg: {}, {}, {}, {}, {}, {}, {}", 123, "abc", 456, "abc", "abc");
替换地方format.find('{', start)改为format.find("{}", start);
感觉用起来方便些

**Comment by Mrliu88888888** [comment]
点赞
